---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# speechbr

<!-- badges: start -->
<!-- badges: end -->

## Overview

The goal of `{speechbr}` is to democratize access to the speeches of the deputies, that is, their ideias and thoughts.

## Installation

You can install the development version of speechbr from [GitHub](https://github.com/) with:

```{r}
# install.packages("devtools")
devtools::install_github("dcardosos/speechbr")
```

## Example

An example of a base searching for the term "pandemia" ("pandemic", in English):

```{r example}
library(speechbr)
library(ggplot2)
library(magrittr)

pandemic <- speechbr::speech_data("pandemia")

dplyr::glimpse(pandemic)
```

A simple application using the base:

```{r example_2}
pandemic %>% 
  dplyr::group_by(partido) %>% 
  dplyr::count(partido) %>% 
  dplyr::ungroup() %>% 
  dplyr::top_n(10, n) %>%
  ggplot(aes(reorder(partido, -n), n)) +
  geom_bar(stat = "identity", fill = "dark red") +
  theme_minimal() +
  labs(
    title = "Qtde de discursos com o termo `pandemia` no período de 50 dias por partido",
    x = "Partido",
    y = "Quantidade de discursos"
  )
```

### Example of a base

```{r example_3}

pandemic %>% 
  head(7) %>%
  knitr::kable()
```
